<?php

namespace Samuca\Fashion\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PosterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosterRepository extends EntityRepository
{  
}
