Samuca\Fashion\Controller\DefaultController:
    home: { pattern: /, method: GET, action: indexAction }
    list:
      pattern: '/list/{page}'
      method: MATCH
      action: listAction
      defaults: { page: 1 }
    show: { pattern: '/show/{id}', method: GET, action: showAction }
    upload: { pattern: /upload, method: POST, action: uploadAction }
    
Samuca\Fashion\Controller\AddressController:
    address: { pattern: /address/, method: get, action: indexAction }
    address_show: { pattern: '/address/{id}/show', method: get, action: showAction }
    address_new: { pattern: /address/new, method: get, action: newAction }
    address_create: { pattern: /address/create, method: post, action: createAction }
    address_edit: { pattern: '/address/{id}/edit', method: get, action: editAction }
    address_update: { pattern: '/address/{id}/update', method: post, action: updateAction }
    address_delete: { pattern: '/address/{id}/delete', method: post, action: deleteAction }
    
Samuca\Fashion\Controller\NetworkController:
    network: { pattern: /network/, method: get, action: indexAction }
    network_show: { pattern: '/network/{id}/show', method: get, action: showAction }
    network_new: { pattern: /network/new, method: get, action: newAction }
    network_create: { pattern: /network/create, method: post, action: createAction }
    network_edit: { pattern: '/network/{id}/edit', method: get, action: editAction }
    network_update: { pattern: '/network/{id}/update', method: post, action: updateAction }
    network_delete: { pattern: '/network/{id}/delete', method: post, action: deleteAction }
    
Samuca\Fashion\Controller\BrandController:
    brand: { pattern: /brand/, method: get, action: indexAction }
    brand_show: { pattern: '/brand/{id}/show', method: get, action: showAction }
    brand_new: { pattern: /brand/new, method: get, action: newAction }
    brand_create: { pattern: /brand/create, method: post, action: createAction }
    brand_edit: { pattern: '/brand/{id}/edit', method: get, action: editAction }
    brand_update: { pattern: '/brand/{id}/update', method: post, action: updateAction }
    brand_delete: { pattern: '/brand/{id}/delete', method: post, action: deleteAction }
    
Samuca\Fashion\Controller\MediaController:
    media: { pattern: /media/, method: get, action: indexAction }
    media_show: { pattern: '/media/{id}/show', method: get, action: showAction }
    media_new: { pattern: /media/new, method: get, action: newAction }
    media_create: { pattern: /media/create, method: post, action: createAction }
    media_edit: { pattern: '/media/{id}/edit', method: get, action: editAction }
    media_update: { pattern: '/media/{id}/update', method: post, action: updateAction }
    media_delete: { pattern: '/media/{id}/delete', method: post, action: deleteAction }
